### ISSUE TITLE
 Stream Deck Mini

### ISSUE THREAD

**Issue by blendmx** [SmokeyMcBong/StreamDeckMonitor#1]
Hello, thanks for making this program, it's just what I needed to get a Stream Deck.

I want to buy the new Mini, do you think this version will work with your app?

Thanks!

**Comment by SmokeyMcBong** [comment]
Hi mate, thank you for the kind words and your interest in this little project,

In theory it should be able to be adapted for use with the StreamDeck Mini, this would depend on the StreamDeck interface library (StreamDeckSharp) and whether that would need updating from the developer to add support for the mini version.

As far as running StreamDeckMonitor out of the box on the mini version (if the interface support is there)  it would need a little work to change the layout from 15 to 6 buttons and what info is shown etc, but it should be do-able

Unfortunately life is extremely busy and up in the air at the moment, I do have little downtime here and there and will keep an eye on this and the StreamDeckSharp interface library to see if support is needed/added for the mini
If the support is added or not needed then i will see what i can do as it shouldn't take too much work to get done,  but free time is very random and sporadic unfortunately 

Hope this helps mate 


Take care 

SmokeyMcBong

**Comment by wischi-chr** [comment]
Hi guys. I'm the developer of StreamDeckSharp.

I'd love to add support for the StreamDeck Mini to my library but atm I don't plan on buying one and without the hardware it would be hard to test it.
If someone is willing to donate a StreamDeck Mini I could implement it.

Another option would be to work with someone that owns a SD-Mini to test it but unfortunately I don't know anybody that owns one.

**Comment by blendmx** [comment]
Thanks for the response, you guys rock. 

I ordered the Mini but it’s taking at least 2 more weeks to arrive to Mexico City. 

I would love to help but I’m not a programmer :( but as soon as the Mini arrives I’ll test it and give you the results. 

Again, thanks for creating this cool app. 

I’ll keep you informed. 

Greetings from Mexico City.

**Comment by SmokeyMcBong** [comment]
@wischi-chr, I'm incredibly humbled.  I would just like to say thank you so much for your work on your StreamDeckSharp library!, these little project's would not have been possible without you!  

@blendmx, I will put together a new test layout template for the mini when i get some free time next week, ready for when you receive your mini Streamdeck. Thank you again for all the kind words! :)

Hope you both have a great weekend! 

Take care

SmokeyMcBong

**Comment by blendmx** [comment]
Wow, thanks a lot!

Got my Stream Deck Mini today and tried running the app, sadly nothing displays on any button, changed some settings on the Configurator but nothing happens.

Again, thanks for giving away your free time to update this cool project :)

Have a great week.

James

**Comment by wischi-chr** [comment]
@blendmx my stream deck mini arrived on saturday ;-)
I'm currently adding support to StreamDeckSharp for the new Mini  (it already works, but a few things still need to be refactored)

**Comment by wischi-chr** [comment]
@SmokeyMcBong @blendmx I refactored a lot of stuff in `StreamDeckSharp`. There is now a generic `OpenMacroBoard.SDK` and a virtual macro board provider called `OpenMacoBoard.VirtualBoard` to allow development without stream deck hardware. Stream Deck Mini is now supported.

The changes are **not** backwards compatable, that means a few names and apis changed but the upgrade should be simple.

Let me know if you need anything.

PS: The new versions are already on nuget, the releases as zip (via github.com) are comming soon.

**Comment by SmokeyMcBong** [comment]
@wischi-chr That's brilliant! thank you so much for all your work mate!  
I should have a little free time over the weekend , I will grab it via nuget and upgrade the project
Also, awesome idea adding the VirtualBoard
Thanks again mate! 

Have a great weekend! 👍

**Comment by SmokeyMcBong** [comment]
@blendmx Hi mate, hope you had a good weekend. 
I had a little time here and there over the weekend, I've put together a quick build 

~~https://github.com/SmokeyMcBong/StreamDeckMonitor/releases/tag/v7.0-Testing~~

10/09 - v7.6 is available from the releases section

**Comment by blendmx** [comment]
Whoa thats awesome!
I was traveling last week and just saw this today, I'll get it as soon I get home after work.

Again, thanks a lot for your work 😀

J
